server:
  port: 8080

spring:
  application:
    name: gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
  data:
    redis:
      host: ${TASKE_REDIS_HOST}
      port: ${TASKE_REDIS_PORT}
      password: ${TASKE_REDIS_PW}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://${AUTH_HOST}:${AUTH_PORT}
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: task-service
              uri: http://${TASK_HOST}:${TASK_PORT}
              predicates:
                - Path=/task/**
              filters:
                - StripPrefix=1

            # - id: user-service
            #   uri: http://localhost:8082
            #   predicates:
            #     - Path=/users/**
            #   filters:
            #     - StripPrefix=1

jwt:
  accesstoken:
    secret: ${TASKE_JWT_ACCESS_SECRET}

#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    reactor.netty: TRACE
#
